# -*- coding: utf-8 -*-
"""TransciptWolof.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Akor9HhAdQKn-ST5Y32KHiRkGrNDaQLz
"""

pip install transformers

pip install wolof   #importation de la bibliotheque wolof de abdouaziz

!gdown --id 1wRiwaQmGi3dotcPgs7-vKt-o9JBN4I-n

from wolof import Speech2Text # from wolof we import Swpeech2Text 
from IPython.display import Audio

asr = Speech2Text(model_name="abdouaziiz/wav2vec2-xls-r-300m-wolof") #chargement du modéle

pip install speechrecognition #installation de speechrecognition

pip install --upgrade pip

pip install pyaudio # installation de pyaudio

import speech_recognition as sr #importation de speechRecognition
r = sr.Recognizer()
micro = sr.Microphone() #utilisation du microphone pour l'enregistrement audio
with micro as source:
    print ("speak")
    audio_data = r.listen(source)  #récuperation de l'audio via le microphone
    print("end")
Audio(audio_data)   
prediction = asr(audio_data)  #transcription de l'audio en texte
prediction